-- NEUTRALIZED (P1-K fix, 2026-05-01)
--
-- This migration previously dropped anon_read/update_responses and anon_delete_answer_items,
-- then created owners_update_responses and owners_delete_answer_items.
-- All of those policies are fully managed (dropped and recreated correctly) by:
--   - 20260428_consolidate_rls_policies.sql
--   - 20260501_enforce_rls_final_state.sql  (authoritative idempotent final state)
--
-- The SQL was replaced with a no-op to prevent any intermediate state issues
-- in fresh environments. Do not restore the original statements.
SELECT 1; -- no-op
