-- NEUTRALIZED (P1-K fix, 2026-05-01)
--
-- This migration previously dropped and recreated anon_read_responses, anon_update_responses,
-- and anon_delete_answer_items (v2 of the P0 fix attempt). Those policies were removed
-- permanently by:
--   - 20260430_fix_rls_responses_answer_items_profiles.sql
--   - 20260501_enforce_rls_final_state.sql  (authoritative idempotent final state)
--
-- The SQL was replaced with a no-op to prevent creation of insecure policies
-- in fresh environments, even transiently. Do not restore the original statements.
SELECT 1; -- no-op
