-- NEUTRALIZED (P1-K fix, 2026-05-01)
--
-- This migration previously created owners_read_responses_v2, owners_delete_responses_v2,
-- and owners_read_answer_items_v2 (with DO/EXCEPTION guard). Those _v2 policies are
-- dropped by 20260428_consolidate_rls_policies.sql and replaced with canonical names.
-- The definitive policy set is enforced by:
--   - 20260428_consolidate_rls_policies.sql
--   - 20260501_enforce_rls_final_state.sql  (authoritative idempotent final state)
--
-- The SQL was replaced with a no-op to prevent any intermediate state issues
-- in fresh environments. Do not restore the original statements.
SELECT 1; -- no-op
