-- NEUTRALIZED (P1-K fix, 2026-05-01)
--
-- This migration previously created RLS policies for anon access on forms, responses,
-- and answer_items. Those policies were superseded and then REMOVED by later migrations:
--   - 20260428_consolidate_rls_policies.sql  (drops and recreates the correct set)
--   - 20260430_fix_rls_responses_answer_items_profiles.sql  (removes anon read/update/delete)
--   - 20260430_fix_security_definer_public_access_whatsapp_logs.sql  (removes anon_read_published_forms)
--   - 20260501_enforce_rls_final_state.sql  (authoritative idempotent final state)
--
-- The SQL was replaced with a no-op to prevent creation of insecure policies
-- in fresh environments, even transiently. Do not restore the original statements.
SELECT 1; -- no-op
